### ISSUE TITLE
Browser audio playback issue

### ISSUE THREAD

**Issue by anouarmaalej** [agszn/highlight-text-in-sync-with-audio#1]
Hi. Is there a workaround to the following error: 
"Error: You will not be able to do the read-along audio because your browser is not able to play MP3, Ogg, or WAV audio formats."
Thanks.
![image](https://user-images.githubusercontent.com/61330141/157516153-6d12fb50-eb80-4578-8213-c12579de7a9b.png)

**Comment by Landobas** [comment]
Just change the audio, put in the src yours. That should solve your problem

**Comment by anouarmaalej** [comment]
Thanks a lot.
